# Site settings
title: iamjrp
description: 'A Thinker, Innovator, Enthusiastic Software Developer, Amateur sketch maker, Recreational Singer, Thought leader and Sometimes clumsy. :-)'
url: 'https://jrphub.github.io/'
baseurl: ''
google_analytics: 'UA-111388814-1'
disqus_shortname: 'iamjrp'

author:
  name: 'Jyoti Ranjan Pattnaik'
  email: mailme@iamjrp.com
# twitter_username: jrp
  facebook_username: jrpattnaik
  github_username:  jrphub
  linkedin_username:  iamjrp

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge
future: true

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
plugins:
  - jekyll-sitemap
  - jekyll-paginate
